=================================
How to Use 102-custom_matrix_mul.py
=================================

This module defines a matrix multiplication function
``custom_matrix_mul(m_a, m_b)``.

Usage
=====

``custom_matrix_mul(...)`` returns a new matrix representing the multiplication
of ``m_a`` by ``m_b``.

::

    >>> custom_matrix_mul = __import__('102-custom_matrix_mul').custom_matrix_mul
    >>> m_a = [
    ... [2, 4],
    ... [6, 8],
    ... ]
    >>> m_b = m_a
    >>> print(custom_matrix_mul(m_a, m_b))
    [[28 40]
     [60 88]]

::

    >>> m_a = [[2, 4]]
    >>> m_b = [
    ... [6, 8],
    ... [10, 12]
    ... ]
    >>> print(custom_matrix_mul(m_a, m_b))
    [[52 64]]

The function also works with floating-point numbers.

::

    >>> m_a = [
    ... [2.2, 4.4, 6.6],
    ... [8.8, 10.1, -12.2]
    ... ]
    >>> m_b = [
    ... [6.6, 8.8],
    ... [-12.2, 10.1],
    ... [4.4, -6.6]
    ... ]
    >>> print(custom_matrix_mul(m_a, m_b))
    [[ 65.56  87.12]
     [-199.96  237.23]]

A minimum of two arguments must be provided.

::

    >>> print(custom_matrix_mul(m_a))
    Traceback (most recent call last):
    TypeError: custom_matrix_mul() missing 1 required positional argument: 'm_b'

::

    >>> print(custom_matrix_mul()) # doctest: +NORMALIZE_WHITESPACE
    Traceback (most recent call last):
    TypeError: custom_matrix_mul() missing 2 required positional arguments: 
    'm_a' and 'm_b'

ValueErrors
===========

If two matrices cannot be multiplied (i.e., the row count of ``m_a`` is not
equal to the column count in ``m_b``), a ValueError is raised.

::

    >>> m_a = [
    ... [2, 4],
    ... [6, 8],
    ... ]
    >>> m_b = [
    ... [2, 4],
    ... [4, 6],
    ... [8, 10]
    ... ]
    >>> print(custom_matrix_mul(m_a, m_b))
    Traceback (most recent call last):
    ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)


The parameters ``m_a`` and ``m_b`` cannot be empty. Otherwise, a ValueError
is raised.

::

    >>> print(custom_matrix_mul([[]], [[2, 4], [6, 8]]))
    Traceback (most recent call last):
    ValueError: shapes (1,0) and (2,2) not aligned: 0 (dim 1) != 2 (dim 0)

::

    >>> print(custom_matrix_mul([[2, 4], [6, 8]], [[]]))
    Traceback (most recent call last):
    ValueError: shapes (2,2) and (1,0) not aligned: 2 (dim 1) != 1 (dim 0)

Invalid Matrices
================

The parameters ``m_a`` and ``m_b`` must be lists. If either parameter is
not a list, a ValueError is raised.

::

    >>> print(custom_matrix_mul("not a list", [[2, 4]]))
    Traceback (most recent call last):
    ValueError: Scalar operands are not allowed, use '*' instead

::

    >>> print(custom_matrix_mul([[2, 4]], "also not a list"))
    Traceback (most recent call last):
    ValueError: Scalar operands are not allowed, use '*' instead

::

    >>> print(custom_matrix_mul("not a list", "also not a list"))
    Traceback (most recent call last):
    ValueError: Scalar operands are not allowed, use '*' instead

If either parameter is ``None``, a TypeError is raised.

::

    >>> print(custom_matrix_mul(None, None))
    Traceback (most recent call last):
    TypeError: Object arrays are not currently supported

Not just any list - they *must* be lists of lists! Otherwise, behavior is
undefined.

::

    >>> print(custom_matrix_mul([2, 4], [[6, 8]]))
    Traceback (most recent call last):
    ValueError: shapes (2,) and (1,2) not aligned: 2 (dim 0) != 1 (dim 0)

::

    >>> print(custom_matrix_mul([[2, 4]], [6, 8]))
    [20]

::

    >>> print(custom_matrix_mul([2, 4], [6, 8]))
    20

And not just any list of lists - they *must* be lists of lists containing
integers or floats! Otherwise, a ValueError or TypeError is raised

::

    >>> print(custom_matrix_mul([[2, "non-number"]], [[6, 8]]))
    Traceback (most recent call last):
    ValueError: shapes (1,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)

::

    >>> print(custom_matrix_mul([[2, 4], [6, 8]], [[6, "8"], [7, 8]]))
    Traceback (most recent call last):
    TypeError: invalid data type for einsum

::

    >>> print(custom_matrix_mul([[2, "non-number"]], [[{"a": 2}, 8.8]]))
    Traceback (most recent call last):
    TypeError: Object arrays are not currently supported

Finally, the length of all rows in matrices ``m_a`` and ``m_b`` should be
equivalent. Otherwise, a ValueError is raised.

::

    >>> m_a = [
    ... [2, 4],
    ... [6, 8, 10]
    ... ]
    >>> m_b = [
    ... [2, 4],
    ... [6, 8]
    ... ]
    >>> print(custom_matrix_mul(m_a, m_b))
    Traceback (most recent call last):
    ValueError: setting an array element with a sequence.

::

    >>> m_a = [
    ... [2, 4],
    ... [6, 8]
    ... ]
    >>> m_b = [
    ... [2, 4],
    ... [6, 8, 10]
    ... ]
    >>> print(custom_matrix_mul(m_a, m_b))
    Traceback (most recent call last):
    ValueError: setting an array element with a sequence.

::

    >>> m_a = [
    ... [2, 4],
    ... [6, 8, 10]
    ... ]
    >>> m_b = m_a
    >>> print(custom_matrix_mul(m_a, m_b))
    Traceback (most recent call last):
    ValueError: setting an array element with a sequence.
